#!/bin/bash
#SBATCH -J run_HDMA
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-20:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# delete everything in the results folder and then run this pipeline to get clean results
# it may need to be restarted more than once if it times out
# example use: sbatch All_HDMA 

cd $SLURM_SUBMIT_DIR

module load singularity

#================
# load/install all libraries
#================

#only need to run this once to install all required packages
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "0_HDMA_setup.Rmd"))'

#================
# DO data prep
#================

#<5 min
singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "1.DO", "1a.Trait_Selection.Rmd"))'

#<5 min
singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "1.DO", "1b.Tissue_Expression.Rmd"))'

#<5 min
singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "1.DO", "2a.Kinship_Expression_Traits.Rmd"))'

#~9.5 hrs
singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "1.DO", "3a.Imputation.Rmd"))'

#total time: 9.75 hrs

#================
# run HDM
#================

#~4.5 hrs
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "1.DO", "3b.High_Dimensional_Mediation.Rmd"))'

#total time: 4.5 hrs

#================
# CC-RIX data prep
#================

#parse phenotypes and gene expression
#<5min
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "2.CC-RIX", "1a.CC-RIX_Phenotypes_Expression.Rmd"))'

#build genotype object
#<1min
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "2.CC-RIX", "1b.CC-RIX_Genotypes.Rmd"))'

#impute CC-RIX gene expression
#<2min
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "2.CC-RIX", "2.Impute_CC-RIX_gene_expression.Rmd"))'

#total time: 8 min
#================
# CC-RIX validation
#================

#predict metabolic index with measured transcripts
#<2min
use_cc_imputed_transcriptome=FALSE
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "2.CC-RIX", "3.CC-RIX_validation.Rmd"))' --args "$use_cc_imputed_transcriptome"
#mv Documents/1.manuscript/2.CC-RIX/3.CC-RIX_validation.html Documents/1.manuscript/2.CC-RIX/3.CC-RIX_validation_measured.html

#predict metabolic index with imputed transcripts
#<2min
use_cc_imputed_transcriptome=TRUE
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "2.CC-RIX", "3.CC-RIX_validation.Rmd"))' --args "$use_cc_imputed_transcriptome"
#mv Documents/1.manuscript/2.CC-RIX/3.CC-RIX_validation.html Documents/1.manuscript/2.CC-RIX/3.CC-RIX_validation_imputed.html

#total time: 4 min

#================
# Human validation
#================

#Cell-type-specific gene expression
#<2min
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "3.Human", "4.Cell_Type_Validation.Rmd"))'

#Look at apelin module more closely
#<1min
gene_set_name=Autophagy_-_animal_cluster.txt
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "3.Human", "4.Gene_Set_Validation.Rmd"))' --args "$gene_set_name"

#Predictions of human metabolic index using HDMA results
#~2 min
#singularity exec ../../../Containers/islet_hdma.sif R -e 'rmarkdown::render(here::here("Documents", "1.manuscript", "3.Human", "4.Human_Data_Validation.Rmd"))'

#total time: 5 min

#================
# Total time: <15 hrs
#================
