---
title: "Individual Gene Follow-Up"
author: Anna L Tyler
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
---

## Introduction

This workflow will be used to build up vignettes of individual
genes in collaboration with Jeff Harder who is working with the
three bears data.

```{r load_code}
rm(list = ls())
is.interactive = FALSE
#is.interactive = TRUE
library("here")

all.fun <- list.files(here("Code"), full.names = TRUE, pattern = ".R")
for(i in 1:length(all.fun)){source(all.fun[i])}
```

```{r load_libraries, message = FALSE, warning = FALSE, error = FALSE}
all.packages <- c("pheatmap", "gprofiler2", "igraph")
load_libraries(all.packages)
```

```{r set_var}
tissue.names <- c("Adipose", "Islet", "Liver", "SkeletalMuscle")
gene.cols <- categorical_pal(8)

#test.genes <- c("Pnpla2", "Mogat2", "Hadha", "Cpt2", "Capn3", "Ccl2", "Prkaa1", "Prkaa2") #from Jeff Harder
test.genes <- "Mest"

```


```{r load_data}
hdma.results.dir <- here("Results", "DO", "High_Dim_Med", "tissue_together-_-complete_mediation")
tissue.loadings <- readRDS(file.path(hdma.results.dir, "Loadings_Transcripts_0.RDS"))
```


```{r genes, fig.width = 10, fig.height = 5}

gene.table <- gconvert(test.genes, organism = "mmusculus")

gene.loading.table <- NULL
for(g in 1:nrow(gene.table)){
	gene.name <- gene.table[g,"input"]
	gene.id <- gene.table[g,"target"]
	
	gene.loading <- sapply(tissue.loadings, function(x) if(length(which(rownames(x) == gene.id)) > 0){x[which(rownames(x) == gene.id)]}else{0})
	names(gene.loading) <- tissue.names
	gene.loading.table <- rbind(gene.loading.table, gene.loading)	
}

rownames(gene.loading.table) <- gene.table[,"input"]

barplot(gene.loading.table, beside = TRUE, col = gene.cols[1:nrow(gene.table)], main = "Loading")
legend("topright", fill = gene.cols[1:nrow(gene.table)], legend = gene.table[,"input"], cex = 0.7)
abline(h = 0)
```

How large are these loadings?
For each gene in each tissue, we looked at how many genes met or exceeded the loadings
of the gene.

```{r rel_mge, fig.width = 4, fig.height = 4}
loading.percentile <- matrix(NA, nrow = nrow(gene.loading.table), ncol = ncol(gene.loading.table))
dimnames(loading.percentile) <- dimnames(gene.loading.table)

for(tx in 1:length(tissue.names)){

    loading.pos.idx <- which(gene.loading.table[,tx] > 0)
    loading.neg.idx <- which(gene.loading.table[,tx] < 0)

    if(length(loading.pos.idx) > 0){
        #pos.gene.perc <- sapply(gene.loading.table[loading.pos.idx,tx], function(x) c(length(which(tissue.loadings[[tx]] >= x)),length(tissue.loadings[[tx]])))
        #rownames(pos.gene.perc) <- c("rank", "total")
        pos.gene.perc <- 1 - sapply(gene.loading.table[loading.pos.idx,tx], function(x) length(which(tissue.loadings[[tx]] >= x))/length(tissue.loadings[[tx]]))
        loading.percentile[loading.pos.idx,tx] <- pos.gene.perc
    }

    if(length(loading.neg.idx) > 0){
        neg.gene.perc <- 1 - sapply(gene.loading.table[loading.neg.idx,tx], function(x) length(which(tissue.loadings[[tx]] <= x))/length(tissue.loadings[[tx]]))
        loading.percentile[loading.neg.idx,tx] <- neg.gene.perc
    }

}
pheatmap(loading.percentile, display_numbers = TRUE, cluster_cols = FALSE, cluster_rows = FALSE,
    main = "Loading percentile")
```

